<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>AvlCommand</AssemblyName>
    <RootNamespace>AvlCommand</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JotunnLib" Version="2.27.1" />
    <PackageReference Include="Digitalroot.Valheim.Common.References" Version="0.219.14" />
  </ItemGroup>

</Project>