name: Build Valheim Mod

on:
  push:
    branches:
      - main
      - develop
      - experimental/**
      - ci-testing

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: microsoft/setup-msbuild@v1.3
      - uses: NuGet/setup-nuget@v2

      - name: Restore
        run: dotnet restore src/AvlCommand/AvlCommand.csproj

      - name: Build
#        run: msbuild YourMod.sln /p:Configuration=Release
#        run: msbuild src/AvlCommand/AvlCommand.csproj /p:Configuration=Release
        run: dotnet build src/AvlCommand/AvlCommand.csproj -c Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ValheimMod-${{ github.ref_name }}
          path: |
            **/bin/Release/*.dll
